### ISSUE TITLE
Force option for overwriting or not

### ISSUE THREAD

**Issue by d0wnblog** [eigenein/imap-utilities#1]
Is it possible to get an option which doesn't ask for overwriting and don't overwrite anything... This would be great for incremental backups :)

**Comment by eigenein** [comment]
You can now use two options:

* `--skip-existing` doesn't overwrite existing files without prompt.
* `--uid-file` specifies a text file that stores last fetched message UID. The file is updated on each run and download will then start from this stored UID. So, it's possible to do incremental backups like this: `download-folder.py --user <user> --password <password> --host imap.gmail.com -f "[Gmail]/Drafts" -d drafts --uid-file uid.txt`.
